<form class="d-xl-flex flex-column justify-content-xl-center align-items-xl-start" id="github">
                            <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center"><label class="d-flex d-sm-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-xl-center align-items-xl-center" style="color: #ffffff;margin-right: 10px;">Repository Name&nbsp;<i class="fa fa-chevron-right"></i></label>
                                <input
                                    class="bg-light border rounded-0 form-control" type="text" placeholder="Repo Name"></div>
                            <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center"><label class="d-flex d-sm-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-xl-center align-items-xl-center" style="color: #ffffff;margin-right: 10px;">Repository Link &nbsp; &nbsp;&nbsp;<i class="fa fa-chevron-right"></i></label>
                                <input
                                    class="bg-light border rounded-0 form-control" type="text" placeholder="Repo Link"></div>
                            <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center"><label class="d-flex d-sm-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-xl-center align-items-xl-center" style="color: #ffffff;margin-right: 10px;">Repository Boolean<i class="fa fa-chevron-right"></i></label>
                                <input
                                    class="bg-light border rounded-0 form-control" type="text" placeholder="Repo Bool"></div>
                            <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center"><label class="d-flex d-sm-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-xl-center align-items-xl-center" style="color: #ffffff;margin-right: 10px;">Repository Description<i class="fa fa-chevron-right"></i></label>
                                <textarea
                                    class="form-control" placeholder="Write about your project"></textarea>
                            </div>
                            <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center"><button class="btn btn-primary bg-light border-primary" type="button" style="color: #000000;">create</button></div>
                        </form>